# Get all pilots (users)
// @no-cookie-jar
GET http://localhost:9080/aviation/api/pilots/
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
###

# Add new pilot
PUT http://localhost:9080/aviation/api/pilots/962ad41d-f371-4892-b472-5fcbff45d357
Content-Type: application/json

{
    "login": "brolan",
    "password": "qwerty",
    "pilotName": "Olaf Brolan",
    "rank": "MAJOR"
}

###