### admin YWRtaW46YWRtaW5hZG1pbg== | user cm9iZXJ0OnVzZXJ1c2Vy | invalid aW52YWxpZDppbnZhbGlk
# Get all pilots (admin)
// @no-cookie-jar
GET http://localhost:9080/aviation/api/pilots/
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
###

# Get all pilots (user) should return 403 Forbidden
// @no-cookie-jar
GET http://localhost:9080/aviation/api/pilots/
Authorization: Basic cm9iZXJ0OnVzZXJ1c2Vy
###

# Add new pilot
PUT http://localhost:9080/aviation/api/pilots/962ad41d-f371-4892-b472-5fcbff45d357
Content-Type: application/json

{
    "login": "brolan",
    "password": "qwerty",
    "pilotName": "Olaf Brolan",
    "rank": "MAJOR"
}

###